# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: いまさらDirect3D11入門
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  初めてグラフィックスAPIを触る人に向けて、Direct3D11の各種機能を説明するサイト
twitter_username:
github_username:  tositeru

repository: tositeru/ImasaraDX11
permalink: /:title
url: 

layout: post
# Build settings
markdown: kramdown
